### ISSUE TITLE
Missing HS in Kafka

### ISSUE THREAD

**Issue by ravindranathakila** [kow3ns/kubernetes-kafka#2]
Please include this in mini:
```
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-hs
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: client
  clusterIP: None
  selector:
    app: kafka
```
