### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by EricVS** [kow3ns/kubernetes-kafka#4]
Hi,
I'm trying to use your template to setup Kafka/Zookeeper on Kubernetes but am having a hard time understanding the link between PersistentVolume and volumeClaimTemplates. 
Would you mind commenting on how to create the PersistentVolume pointing to a local path? 
I have this setup, but when I apply your manifest I get the error below...
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir
  labels:
    type: local
spec:
  storageClassName: datadir
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/kubernetes/zk/config"
```
Error is:
```
PersistentVolumeClaim is not bound: "datadir-zk-0" (repeated 6 times)
```
and the Persistent Volume Claims stay in pending.

Any help is greatly appreciated.

Kind regards, 

Eric V.

**Comment by sibtainabbas10** [comment]
I had the same issue. What I did was I created a `PersistentVolume` using

```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: kafka-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ec2-user/kafka-data"
```
Then in the kafka-config i added:

```
-----------
-----------
        volumeMounts:
        - name: kafka-pv-volume
          mountPath: /var/lib/kafka
-----------
-----------
  volumeClaimTemplates:
  - metadata:
      name: kafka-pv-volume
    spec:
      storageClassName: manual
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
```
Let me know if that helps
